In [1]:
import numpy as np
from lib.sis_eq_lin.gauss_jacobi import MetodoIterativoGaussJacobi  

In [2]:
matrizA = np.array([
  [10,1,1],
  [1,10,1],
  [1,1,10]
])

vetorB = np.array([12,12,12])

In [3]:
metodo = MetodoIterativoGaussJacobi(matrizA, vetorB, 1e-10)

In [4]:
metodo.solve()

C Matrix:
 [[ 0.  -0.1 -0.1]
 [-0.1  0.  -0.1]
 [-0.1 -0.1  0. ]]
G Vector:
 [1.2 1.2 1.2]
Alfa: [0. 0. 0.]
Alfa dps de computar: [0.2 0.2 0.2]
Max alfa: 0.2
The matrix C is convergent.

Iteracao: 1
Verificando criterio de parada:
Diff: 1.0 | Tolerance: 1e-10

Iteracao: 2
Verificando criterio de parada:
Diff: 0.25 | Tolerance: 1e-10

Iteracao: 3
Verificando criterio de parada:
Diff: 0.04761904761904766 | Tolerance: 1e-10

Iteracao: 4
Verificando criterio de parada:
Diff: 0.00961538461538467 | Tolerance: 1e-10

Iteracao: 5
Verificando criterio de parada:
Diff: 0.0019193857965450277 | Tolerance: 1e-10

Iteracao: 6
Verificando criterio de parada:
Diff: 0.00038402457757290466 | Tolerance: 1e-10

Iteracao: 7
Verificando criterio de parada:
Diff: 7.679901697257075e-05 | Tolerance: 1e-10

Iteracao: 8
Verificando criterio de parada:
Diff: 1.5360039321720466e-05 | Tolerance: 1e-10

Iteracao: 9
Verificando criterio de parada:
Diff: 3.0719984274072186e-06 | Tolerance: 1e-10

Iteracao: 10
Verifica

array([1., 1., 1.])

In [5]:
metodo.solution

array([1., 1., 1.])