In [2]:
import numpy as np
from lib.sis_eq_lin.gauss_jacobi import MetodoIterativoGaussJacobi  

In [3]:
matrizA = np.array([
  [10,1,1],
  [1,10,1],
  [1,1,10]
])

vetorB = np.array([12,12,12])

In [4]:
metodo = MetodoIterativoGaussJacobi(matrizA, vetorB)

In [5]:
metodo.solve()

C Matrix:
 [[ 0.  -0.1 -0.1]
 [-0.1  0.  -0.1]
 [-0.1 -0.1  0. ]]
G Vector:
 [1.2 1.2 1.2]
Alfa: [0. 0. 0.]
Alfa dps de computar: [0.2 0.2 0.2]
Max alfa: 0.2
The matrix C is convergent.
Iteration: 1


AttributeError: 'MetodoIterativoGaussJacobi' object has no attribute 'x'