In [1]:
import numpy as np
from lib.sis_eq_lin.res_sistemas_triang import ResSisLin
from lib.sis_eq_lin.met_eliminacao_gauss import MetodoEliminacaoGauss
from lib.sis_eq_lin.fatoracao_lu import FatoracaoLU

# Aula 10/06

2 Exercícios para implementar Gauss e Fatoração LU


In [2]:
ex1_a = [[4, -1, 1], [2, 5, 2], [1, 2, 4]]

ex1_b = [8, 3, 11]

In [3]:
ex2_a = [[1, -1 / 2, 1, 0], [2, -1, -1, 1], [1, 1, 0, 0], [1, -1 / 2, 1, 1]]

ex2_b = [4, 5, 2, 5]

In [4]:
# Ex 1 - Gauss

ex1_gauss = MetodoEliminacaoGauss(ex1_a, ex1_b)

print("[EX1 - Gauss] Encontrando triangulares:\n")
solutionMatrix, AUpper, BUpper, factorMatrix = ex1_gauss.findTriangular()

print("[EX1 - Gauss] Encontrando solução do sistema linear:\n")
ex1_solution = ResSisLin(AUpper, BUpper)
solutionVector = ex1_solution.findSolution()
print(f"[EX1 - Gauss] Solução final: {solutionVector}\n")

[EX1 - Gauss] Encontrando triangulares:


Solution matrix POS PIVOT CHANGES:
[[ 4. -1.  1.  8.]
 [ 2.  5.  2.  3.]
 [ 1.  2.  4. 11.]]

Factor in [1,0]: 0.5
Linha i: [2. 5. 2. 3.]
Linha j: [ 4. -1.  1.  8.]
Final: [ 0.   5.5  1.5 -1. ]
Solution matrix on [1,0]: 
 [[ 4.  -1.   1.   8. ]
 [ 0.   5.5  1.5 -1. ]
 [ 1.   2.   4.  11. ]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.  -1.   1.   8. ]
 [ 0.   5.5  1.5 -1. ]
 [ 1.   2.   4.  11. ]]

Factor in [2,0]: 0.25
Linha i: [ 1.  2.  4. 11.]
Linha j: [ 4. -1.  1.  8.]
Final: [0.   2.25 3.75 9.  ]
Solution matrix on [2,0]: 
 [[ 4.   -1.    1.    8.  ]
 [ 0.    5.5   1.5  -1.  ]
 [ 0.    2.25  3.75  9.  ]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.   -1.    1.    8.  ]
 [ 0.    5.5   1.5  -1.  ]
 [ 0.    2.25  3.75  9.  ]]

Factor in [2,1]: 0.4090909090909091
Linha i: [0.   2.25 3.75 9.  ]
Linha j: [ 0.   5.5  1.5 -1. ]
Final: [0.         0.         3.13636364 9.40909091]
Solution matrix on [2,1]: 
 [[ 4.         -1.          1.          8. 

In [5]:
# Ex 1 - LU

ex1_fatLU = FatoracaoLU(ex1_a, ex1_b)

print("[EX1 - Fatoração LU] Encontrando triangulares:\n")
Vx, Vy = ex1_fatLU.findSolution()

print(f"[EX1 - Fatoração LU] Solução final - X = {Vx}, Y = {Vy}\n")

[EX1 - Fatoração LU] Encontrando triangulares:


Solution matrix POS PIVOT CHANGES:
[[ 4. -1.  1.  8.]
 [ 2.  5.  2.  3.]
 [ 1.  2.  4. 11.]]

Factor in [1,0]: 0.5
Linha i: [2. 5. 2. 3.]
Linha j: [ 4. -1.  1.  8.]
Final: [ 0.   5.5  1.5 -1. ]
Solution matrix on [1,0]: 
 [[ 4.  -1.   1.   8. ]
 [ 0.   5.5  1.5 -1. ]
 [ 1.   2.   4.  11. ]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.  -1.   1.   8. ]
 [ 0.   5.5  1.5 -1. ]
 [ 1.   2.   4.  11. ]]

Factor in [2,0]: 0.25
Linha i: [ 1.  2.  4. 11.]
Linha j: [ 4. -1.  1.  8.]
Final: [0.   2.25 3.75 9.  ]
Solution matrix on [2,0]: 
 [[ 4.   -1.    1.    8.  ]
 [ 0.    5.5   1.5  -1.  ]
 [ 0.    2.25  3.75  9.  ]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.   -1.    1.    8.  ]
 [ 0.    5.5   1.5  -1.  ]
 [ 0.    2.25  3.75  9.  ]]

Factor in [2,1]: 0.4090909090909091
Linha i: [0.   2.25 3.75 9.  ]
Linha j: [ 0.   5.5  1.5 -1. ]
Final: [0.         0.         3.13636364 9.40909091]
Solution matrix on [2,1]: 
 [[ 4.         -1.          1.      

In [6]:
# Ex 2 - Gauss

ex2_gauss = MetodoEliminacaoGauss(ex2_a, ex2_b)

print("[EX2 - Gauss] Encontrando triangulares:\n")
solutionMatrix, AUpper, BUpper,_ = ex2_gauss.findTriangular()

print("[EX2 - Gauss] Encontrando solução do sistema linear:\n")
ex2_solution = ResSisLin(AUpper, BUpper)
solutionVector = ex2_solution.findSolution()
print(f"[EX2 - Gauss] Solução final: {solutionVector}\n")

[EX2 - Gauss] Encontrando triangulares:


Solution matrix POS PIVOT CHANGES:
[[ 2.  -1.  -1.   1.   5. ]
 [ 1.  -0.5  1.   0.   4. ]
 [ 1.   1.   0.   0.   2. ]
 [ 1.  -0.5  1.   1.   5. ]]

Factor in [1,0]: 0.5
Linha i: [ 1.  -0.5  1.   0.   4. ]
Linha j: [ 2. -1. -1.  1.  5.]
Final: [ 0.   0.   1.5 -0.5  1.5]
Solution matrix on [1,0]: 
 [[ 2.  -1.  -1.   1.   5. ]
 [ 0.   0.   1.5 -0.5  1.5]
 [ 1.   1.   0.   0.   2. ]
 [ 1.  -0.5  1.   1.   5. ]] 


Solution matrix POS PIVOT CHANGES:
[[ 2.  -1.  -1.   1.   5. ]
 [ 0.   0.   1.5 -0.5  1.5]
 [ 1.   1.   0.   0.   2. ]
 [ 1.  -0.5  1.   1.   5. ]]

Factor in [2,0]: 0.5
Linha i: [1. 1. 0. 0. 2.]
Linha j: [ 2. -1. -1.  1.  5.]
Final: [ 0.   1.5  0.5 -0.5 -0.5]
Solution matrix on [2,0]: 
 [[ 2.  -1.  -1.   1.   5. ]
 [ 0.   0.   1.5 -0.5  1.5]
 [ 0.   1.5  0.5 -0.5 -0.5]
 [ 1.  -0.5  1.   1.   5. ]] 


Solution matrix POS PIVOT CHANGES:
[[ 2.  -1.  -1.   1.   5. ]
 [ 0.   0.   1.5 -0.5  1.5]
 [ 0.   1.5  0.5 -0.5 -0.5]
 [ 1.  -0.5  1.   1

In [7]:
# Ex 2 - Fatoração LU

ex2_LU = FatoracaoLU(ex2_a, ex2_b)

print("[EX2 - Fatoração LU] Encontrando solução:\n")
Vx, Vy = ex2_LU.findSolution()

print(f"[EX2 - Fatoração LU] Encontrando solução do sistema linear: \nVx: {Vx}\n Vy: {Vy} \n")

[EX2 - Fatoração LU] Encontrando solução:


Solution matrix POS PIVOT CHANGES:
[[ 2.  -1.  -1.   1.   5. ]
 [ 1.  -0.5  1.   0.   4. ]
 [ 1.   1.   0.   0.   2. ]
 [ 1.  -0.5  1.   1.   5. ]]

Factor in [1,0]: 0.5
Linha i: [ 1.  -0.5  1.   0.   4. ]
Linha j: [ 2. -1. -1.  1.  5.]
Final: [ 0.   0.   1.5 -0.5  1.5]
Solution matrix on [1,0]: 
 [[ 2.  -1.  -1.   1.   5. ]
 [ 0.   0.   1.5 -0.5  1.5]
 [ 1.   1.   0.   0.   2. ]
 [ 1.  -0.5  1.   1.   5. ]] 


Solution matrix POS PIVOT CHANGES:
[[ 2.  -1.  -1.   1.   5. ]
 [ 0.   0.   1.5 -0.5  1.5]
 [ 1.   1.   0.   0.   2. ]
 [ 1.  -0.5  1.   1.   5. ]]

Factor in [2,0]: 0.5
Linha i: [1. 1. 0. 0. 2.]
Linha j: [ 2. -1. -1.  1.  5.]
Final: [ 0.   1.5  0.5 -0.5 -0.5]
Solution matrix on [2,0]: 
 [[ 2.  -1.  -1.   1.   5. ]
 [ 0.   0.   1.5 -0.5  1.5]
 [ 0.   1.5  0.5 -0.5 -0.5]
 [ 1.  -0.5  1.   1.   5. ]] 


Solution matrix POS PIVOT CHANGES:
[[ 2.  -1.  -1.   1.   5. ]
 [ 0.   0.   1.5 -0.5  1.5]
 [ 0.   1.5  0.5 -0.5 -0.5]
 [ 1.  -0.5  1.  

In [8]:
# Exercicio aula 10/07

In [9]:
A = np.array([[1,-1,2,-1],
              [2, -2,3,-3],
              [1,1,1,0],
              [1,-1,4,3]
              ])

b = np.array([-8,-20,-2,4])



In [12]:
gauss = MetodoEliminacaoGauss(A, b)

solutionMatrix, AUpper, BUpper, factorMatrix = gauss.findTriangular()


Solution matrix POS PIVOT CHANGES:
[[  2.  -2.   3.  -3. -20.]
 [  1.  -1.   2.  -1.  -8.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]

Factor in [1,0]: 0.5
Linha i: [ 1. -1.  2. -1. -8.]
Linha j: [  2.  -2.   3.  -3. -20.]
Final: [0.  0.  0.5 0.5 2. ]
Solution matrix on [1,0]: 
 [[  2.   -2.    3.   -3.  -20. ]
 [  0.    0.    0.5   0.5   2. ]
 [  1.    1.    1.    0.   -2. ]
 [  1.   -1.    4.    3.    4. ]] 


Solution matrix POS PIVOT CHANGES:
[[  2.   -2.    3.   -3.  -20. ]
 [  0.    0.    0.5   0.5   2. ]
 [  1.    1.    1.    0.   -2. ]
 [  1.   -1.    4.    3.    4. ]]

Factor in [2,0]: 0.5
Linha i: [ 1.  1.  1.  0. -2.]
Linha j: [  2.  -2.   3.  -3. -20.]
Final: [ 0.   2.  -0.5  1.5  8. ]
Solution matrix on [2,0]: 
 [[  2.   -2.    3.   -3.  -20. ]
 [  0.    0.    0.5   0.5   2. ]
 [  0.    2.   -0.5   1.5   8. ]
 [  1.   -1.    4.    3.    4. ]] 


Solution matrix POS PIVOT CHANGES:
[[  2.   -2.    3.   -3.  -20. ]
 [  0.    0.    0.5   0.5   2. ]
 [  0.    2. 

In [16]:
ResSisLin(AUpper, BUpper).findSolution()

(4, 1) (4, 4)
Matriz é triangular superior
Received Matrix A:
[[ 2.  -2.   3.  -3. ]
 [ 0.   2.  -0.5  1.5]
 [ 0.   0.   2.5  4.5]
 [ 0.   0.   0.  -0.4]]
Received Vector B:
[[-20. ]
 [  8. ]
 [ 14. ]
 [ -0.8]]
Variation interval for I: range(2, -1, -1)                  with shape (0,3)
Variation Interval for J: range(1, 4)
Initial Solution: [0. 0. 0. 2.]
i: 2
i: 2, j: 3, sum: 9.000000000000002
Solution:
[0. 0. 2. 2.]

i: 1
i: 1, j: 2, sum: -0.9999999999999997
i: 1, j: 3, sum: 2.0000000000000013
Solution:
[0. 3. 2. 2.]

i: 0
i: 0, j: 1, sum: -5.999999999999998
i: 0, j: 2, sum: 0.0
i: 0, j: 3, sum: -6.000000000000002
Solution:
[-7.  3.  2.  2.]

Solution: [-7.  3.  2.  2.]


array([-7.,  3.,  2.,  2.])