In [2]:
import numpy as np
from lib.sis_eq_lin.res_sistemas_triang import ResSisLin
from lib.sis_eq_lin.met_eliminacao_gauss import MetodoEliminacaoGauss

# Aula 10/06

2 Exercícios para implementar Gauss e Fatoração LU

In [4]:
ex1_a = [
  [4,-1,1],
  [2,5,2],
  [1, 2, 4]
]

ex1_b = [
  8,3,11
]

In [5]:
ex2_a = [
  [1, -1/2, 1,0],
  [2,-1,-1,1],
  [1,1,0,0],
  [1,-1/2,1,1]
]

ex2_b = [4,5,2,5]

In [8]:
# Ex 1 - Gauss

ex1_gauss = MetodoEliminacaoGauss(ex1_a, ex1_b)

print("[EX1 - Gauss] Encontrando triangulares:\n")
solutionMatrix, AUpper, BUpper = ex1_gauss.findTriangular()

print("[EX1 - Gauss] Encontrando solução do sistema linear:\n")
ex1_solution = ResSisLin(AUpper, BUpper)
solutionVector = ex1_solution.findSolution()
print(f"[EX1 - Gauss] Solução final: {solutionVector}\n")

Encontrando triangulares:


Solution matrix POS PIVOT CHANGES:
[[ 4. -1.  1.  8.]
 [ 2.  5.  2.  3.]
 [ 1.  2.  4. 11.]]

Factor in [1,0]: 0.5
Linha i: [2. 5. 2. 3.]
Linha j: [ 4. -1.  1.  8.]
Final: [ 0.   5.5  1.5 -1. ]
Solution matrix on [1,0]: 
 [[ 4.  -1.   1.   8. ]
 [ 0.   5.5  1.5 -1. ]
 [ 1.   2.   4.  11. ]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.  -1.   1.   8. ]
 [ 0.   5.5  1.5 -1. ]
 [ 1.   2.   4.  11. ]]

Factor in [2,0]: 0.25
Linha i: [ 1.  2.  4. 11.]
Linha j: [ 4. -1.  1.  8.]
Final: [0.   2.25 3.75 9.  ]
Solution matrix on [2,0]: 
 [[ 4.   -1.    1.    8.  ]
 [ 0.    5.5   1.5  -1.  ]
 [ 0.    2.25  3.75  9.  ]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.   -1.    1.    8.  ]
 [ 0.    5.5   1.5  -1.  ]
 [ 0.    2.25  3.75  9.  ]]

Factor in [2,1]: 0.4090909090909091
Linha i: [0.   2.25 3.75 9.  ]
Linha j: [ 0.   5.5  1.5 -1. ]
Final: [0.         0.         3.13636364 9.40909091]
Solution matrix on [2,1]: 
 [[ 4.         -1.          1.          8.        ]
 [ 0.

array([ 1., -1.,  3.])