In [1]:
import numpy as np
from lib.sis_eq_lin.res_sistemas_triang import ResSisLin


In [2]:
# Exemplo da aula
vec_solucao = np.array([-3, 5, 0])

matrizA = np.array([[3, 2, 4], [1, 1, 2], [4, 3, -2]])
vetorB = np.array([1, 2, 3])

triangularA = np.array([[3, 2, 4], [0, 1 / 3, 2 / 3], [0, 0, -8]])
vetorTriangularB = np.array([1, 5 / 3, 0])

In [3]:
ex1 = ResSisLin(triangularA, vetorTriangularB)

(3,) (3, 3)
Matriz é triangular superior
Received Matrix A:
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]]
Received Vector B:
[1.         1.66666667 0.        ]


In [4]:
ex1.findSolution()

Variation interval for I: range(1, -1, -1) with shape (0,2)
Initial Solution: [ 0.  0. -0.]
i: 1
Solution of (1.6666666666666667 - 0 / 0.3333333333333333):
[ 0.  5. -0.]

i: 0
i: 0, j: 1, sum: 10.000000000000002
Solution of (1.0 - 10.000000000000002 / 3.0):
[-3.  5. -0.]

Solution: [-3.  5. -0.]


array([-3.,  5., -0.])

# Aula 22/05/2024

In [5]:
from lib.sis_eq_lin.met_eliminacao_gauss import MetodoEliminacaoGauss

In [6]:
# Exercício a)

a = np.array([[2,2,1,1],[1,-1,2,-1],[3,2,-3,-2],[4,3,2,1]])
b = np.array([7,1,4,12])

ex_a = MetodoEliminacaoGauss(a,b)

In [7]:
solutionMatrix, AUpper, BUpper = ex_a.findTriangular()

Factor in [1,0]: 0.5
Linha i: [ 1. -1.  2. -1.  1.]
Linha j: [2. 2. 1. 1. 7.]
Final: [ 0.  -2.   1.5 -1.5 -2.5]
Solution matrix on [1,0]: 
 [[ 2.   2.   1.   1.   7. ]
 [ 0.  -2.   1.5 -1.5 -2.5]
 [ 3.   2.  -3.  -2.   4. ]
 [ 4.   3.   2.   1.  12. ]] 

Factor in [2,0]: 1.5
Linha i: [ 3.  2. -3. -2.  4.]
Linha j: [2. 2. 1. 1. 7.]
Final: [ 0.  -1.  -4.5 -3.5 -6.5]
Solution matrix on [2,0]: 
 [[ 2.   2.   1.   1.   7. ]
 [ 0.  -2.   1.5 -1.5 -2.5]
 [ 0.  -1.  -4.5 -3.5 -6.5]
 [ 4.   3.   2.   1.  12. ]] 

Factor in [3,0]: 2.0
Linha i: [ 4.  3.  2.  1. 12.]
Linha j: [2. 2. 1. 1. 7.]
Final: [ 0. -1.  0. -1. -2.]
Solution matrix on [3,0]: 
 [[ 2.   2.   1.   1.   7. ]
 [ 0.  -2.   1.5 -1.5 -2.5]
 [ 0.  -1.  -4.5 -3.5 -6.5]
 [ 0.  -1.   0.  -1.  -2. ]] 

Factor in [2,1]: 0.5
Linha i: [ 0.  -1.  -4.5 -3.5 -6.5]
Linha j: [ 0.  -2.   1.5 -1.5 -2.5]
Final: [ 0.    0.   -5.25 -2.75 -5.25]
Solution matrix on [2,1]: 
 [[ 2.    2.    1.    1.    7.  ]
 [ 0.   -2.    1.5  -1.5  -2.5 ]
 [ 0.    0.   

In [8]:
ex_a_solution = ResSisLin(AUpper, BUpper)

(4, 1) (4, 4)
Matriz é triangular superior
Received Matrix A:
[[ 2.          2.          1.          1.        ]
 [ 0.         -2.          1.5        -1.5       ]
 [ 0.          0.         -5.25       -2.75      ]
 [ 0.          0.          0.          0.14285714]]
Received Vector B:
[[ 7.  ]
 [-2.5 ]
 [-5.25]
 [ 0.  ]]


In [9]:
solution = ex_a_solution.findSolution()

Variation interval for I: range(2, -1, -1) with shape (0,3)
Initial Solution: [0. 0. 0. 0.]
i: 2
Solution of ([-5.25] - 0 / -5.25):
[0. 0. 1. 0.]

i: 1
i: 1, j: 2, sum: 1.5
Solution of ([-2.5] - 1.5 / -2.0):
[0. 2. 1. 0.]

i: 0
i: 0, j: 1, sum: 4.0
i: 0, j: 2, sum: 5.0
Solution of ([7.] - 5.0 / 2.0):
[1. 2. 1. 0.]

Solution: [1. 2. 1. 0.]


In [10]:
# Ex livro

exlivro_a = np.array([[3, 2, 4], [1, 1, 2], [4, 3, -2]], dtype=float)
exlivro_b = np.array([1, 2, 3], dtype=float)

gauss_exlivro = MetodoEliminacaoGauss(exlivro_a, exlivro_b)


In [11]:
print(gauss_exlivro.augmentedMatrix)

[[ 3.  2.  4.  1.]
 [ 1.  1.  2.  2.]
 [ 4.  3. -2.  3.]]


In [12]:
solutionMatrix, AUpper, BUpper = gauss_exlivro.findTriangular()

Factor in [1,0]: 0.3333333333333333
Linha i: [1. 1. 2. 2.]
Linha j: [3. 2. 4. 1.]
Final: [0.         0.33333333 0.66666667 1.66666667]
Solution matrix on [1,0]: 
 [[ 3.          2.          4.          1.        ]
 [ 0.          0.33333333  0.66666667  1.66666667]
 [ 4.          3.         -2.          3.        ]] 

Factor in [2,0]: 1.3333333333333333
Linha i: [ 4.  3. -2.  3.]
Linha j: [3. 2. 4. 1.]
Final: [ 0.          0.33333333 -7.33333333  1.66666667]
Solution matrix on [2,0]: 
 [[ 3.          2.          4.          1.        ]
 [ 0.          0.33333333  0.66666667  1.66666667]
 [ 0.          0.33333333 -7.33333333  1.66666667]] 

Factor in [2,1]: 1.0000000000000002
Linha i: [ 0.          0.33333333 -7.33333333  1.66666667]
Linha j: [0.         0.33333333 0.66666667 1.66666667]
Final: [ 0.00000000e+00  5.55111512e-17 -8.00000000e+00 -4.44089210e-16]
Solution matrix on [2,1]: 
 [[ 3.00000000e+00  2.00000000e+00  4.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  3.33333333e-01  6

In [13]:

print("A:\n", AUpper)
print("B:\n", BUpper)

A:
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]]
B:
 [[1.        ]
 [1.66666667]
 [0.        ]]


In [14]:
solucao_exlivro = ResSisLin(AUpper, BUpper)

(3, 1) (3, 3)
Matriz é triangular superior
Received Matrix A:
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]]
Received Vector B:
[[1.        ]
 [1.66666667]
 [0.        ]]


In [15]:
solucao_exlivro.findSolution()

Variation interval for I: range(1, -1, -1) with shape (0,2)
Initial Solution: [ 0.  0. -0.]
i: 1
Solution of ([1.66666667] - 0 / 0.33333333333333337):
[ 0.  5. -0.]

i: 0
i: 0, j: 1, sum: 10.0
Solution of ([1.] - 10.0 / 3.0):
[-3.  5. -0.]

Solution: [-3.  5. -0.]


array([-3.,  5., -0.])

In [20]:
# Ex 1 da aula 27/5
ex1_a = np.array([[2,2,1,1],[1,-1,2,-1],[3,2,-3,-2],[4,3,2,1]])
ex1_b = np.array([7,1,4,12])

print("--Método de eliminação de Gauss--")
gauss_ex1 = MetodoEliminacaoGauss(ex1_a, ex1_b)

print("Encontrando triangular:\n")
solutionMatrix, AUpper_ex1, BUpper_ex1 = gauss_ex1.findTriangular()

print("--Solucao do sistema--")
solucao_ex1 = ResSisLin(AUpper_ex1, BUpper_ex1)
solucao_ex1.findSolution()

--Método de eliminação de Gauss--
Encontrando triangular:

Factor in [1,0]: 0.5
Linha i: [ 1. -1.  2. -1.  1.]
Linha j: [2. 2. 1. 1. 7.]
Final: [ 0.  -2.   1.5 -1.5 -2.5]
Solution matrix on [1,0]: 
 [[ 2.   2.   1.   1.   7. ]
 [ 0.  -2.   1.5 -1.5 -2.5]
 [ 3.   2.  -3.  -2.   4. ]
 [ 4.   3.   2.   1.  12. ]] 

Factor in [2,0]: 1.5
Linha i: [ 3.  2. -3. -2.  4.]
Linha j: [2. 2. 1. 1. 7.]
Final: [ 0.  -1.  -4.5 -3.5 -6.5]
Solution matrix on [2,0]: 
 [[ 2.   2.   1.   1.   7. ]
 [ 0.  -2.   1.5 -1.5 -2.5]
 [ 0.  -1.  -4.5 -3.5 -6.5]
 [ 4.   3.   2.   1.  12. ]] 

Factor in [3,0]: 2.0
Linha i: [ 4.  3.  2.  1. 12.]
Linha j: [2. 2. 1. 1. 7.]
Final: [ 0. -1.  0. -1. -2.]
Solution matrix on [3,0]: 
 [[ 2.   2.   1.   1.   7. ]
 [ 0.  -2.   1.5 -1.5 -2.5]
 [ 0.  -1.  -4.5 -3.5 -6.5]
 [ 0.  -1.   0.  -1.  -2. ]] 

Factor in [2,1]: 0.5
Linha i: [ 0.  -1.  -4.5 -3.5 -6.5]
Linha j: [ 0.  -2.   1.5 -1.5 -2.5]
Final: [ 0.    0.   -5.25 -2.75 -5.25]
Solution matrix on [2,1]: 
 [[ 2.    2.    1.    

In [19]:
# Ex 2 da aula 27/5 - depende de pivotamento

pivo_a = np.array([[3, -2, 5, 1], [-6, 4, -8, 1], [9, -6, 19, 1], [6, -4, -6, 15]])

pivo_b = np.array([7, -9, 23, 11])

print("--Método de eliminação de Gauss--")
gauss_pivo = MetodoEliminacaoGauss(pivo_a, pivo_b)

print("Encontrando triangular:\n")
solutionMatrix, AUpperPivo, BUpperPivo = gauss_pivo.findTriangular()

--Método de eliminação de Gauss--
Encontrando triangular:

Factor in [1,0]: -2.0
Linha i: [-6.  4. -8.  1. -9.]
Linha j: [ 3. -2.  5.  1.  7.]
Final: [0. 0. 2. 3. 5.]
Solution matrix on [1,0]: 
 [[ 3. -2.  5.  1.  7.]
 [ 0.  0.  2.  3.  5.]
 [ 9. -6. 19.  1. 23.]
 [ 6. -4. -6. 15. 11.]] 

Factor in [2,0]: 3.0
Linha i: [ 9. -6. 19.  1. 23.]
Linha j: [ 3. -2.  5.  1.  7.]
Final: [ 0.  0.  4. -2.  2.]
Solution matrix on [2,0]: 
 [[ 3. -2.  5.  1.  7.]
 [ 0.  0.  2.  3.  5.]
 [ 0.  0.  4. -2.  2.]
 [ 6. -4. -6. 15. 11.]] 

Factor in [3,0]: 2.0
Linha i: [ 6. -4. -6. 15. 11.]
Linha j: [ 3. -2.  5.  1.  7.]
Final: [  0.   0. -16.  13.  -3.]
Solution matrix on [3,0]: 
 [[  3.  -2.   5.   1.   7.]
 [  0.   0.   2.   3.   5.]
 [  0.   0.   4.  -2.   2.]
 [  0.   0. -16.  13.  -3.]] 

Factor in [2,1]: nan
Linha i: [ 0.  0.  4. -2.  2.]
Linha j: [0. 0. 2. 3. 5.]
Final: [nan nan nan nan nan]
Solution matrix on [2,1]: 
 [[  3.  -2.   5.   1.   7.]
 [  0.   0.   2.   3.   5.]
 [ nan  nan  nan  nan  n

/home/tone/www/ufsm/cadeiras/metodos-numericos/lib/sis_eq_lin/met_eliminacao_gauss.py:30: RuntimeWarning: invalid value encountered in scalar divide
  factor = self.solutionMatrix[i][j] / self.solutionMatrix[j][j]


In [ ]:
print("--Solucao do sistema--")
solucao_pivo = ResSisLin(AUpperPivo, BUpperPivo)
solucao_pivo.findSolution()