In [1]:
import numpy as np
from lib.sis_eq_lin.res_sistemas_triang import ResSisLin


In [2]:
# Exemplo da aula
vec_solucao = np.array([-3, 5, 0])

matrizA = np.array([[3, 2, 4], [1, 1, 2], [4, 3, -2]])
vetorB = np.array([1, 2, 3])

triangularA = np.array([[3, 2, 4], [0, 1 / 3, 2 / 3], [0, 0, -8]])
vetorTriangularB = np.array([1, 5 / 3, 0])

In [3]:
ex1 = ResSisLin(triangularA, vetorTriangularB)

(3,) (3, 3)
Matriz é triangular superior
Received Matrix A:
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]]
Received Vector B:
[1.         1.66666667 0.        ]


In [4]:
ex1.findSolution()

Variation interval for I: range(0, 2) with shape 3
Initial Solution: [ 0.  0. -0.]
variationInterval range(0, 2)
i: 0
i: 0, j: 0, sum: 0
i: 0, j: 1, sum: 9.0
i: 0, j: 2, sum: 9.0
i: 1
i: 1, j: 1, sum: 0
i: 1, j: 2, sum: 0.1111111111111111
Solution: [-2.66666667  4.66666667 -0.        ]


array([-2.66666667,  4.66666667, -0.        ])

# Aula 22/05/2024

In [7]:
from lib.sis_eq_lin.met_eliminacao_gauss import MetodoEliminacaoGauss

In [8]:
# Exercício a)

a = np.array([[2,2,1,1],[1,-1,2,-1],[3,2,-3,-2],[4,3,2,1]])
b = np.array([7,1,4,12])

ex_a = MetodoEliminacaoGauss(a,b)

In [10]:
solutionMatrix, AUpper, BUpper = ex_a.findTriangular()

Factor in [1,0]: 0.5
Factor in [2,0]: 1.5
Factor in [3,0]: 2.0
Factor in [2,1]: 0.5
Factor in [3,1]: 0.5
Factor in [3,2]: -0.0
Solution Matrix:
[[ 2  2  1  1  7]
 [ 0 -2  1 -1 -2]
 [ 0  0 -4 -2 -5]
 [ 0  0  0  0 -1]]
AUpper:
[[ 2  2  1  1]
 [ 0 -2  1 -1]
 [ 0  0 -4 -2]
 [ 0  0  0  0]]
BUpper:
[[ 7]
 [-2]
 [-5]
 [-1]]


In [11]:
ex_a_solution = ResSisLin(AUpper, BUpper)

(4, 1) (4, 4)
Matriz é triangular superior
Received Matrix A:
[[ 2  2  1  1]
 [ 0 -2  1 -1]
 [ 0  0 -4 -2]
 [ 0  0  0  0]]
Received Vector B:
[[ 7]
 [-2]
 [-5]
 [-1]]


In [14]:
solution = ex_a_solution.findSolution()

Variation interval for I: range(0, 3) with shape 4
Initial Solution: [  0.   0.   0. -inf]
variationInterval range(0, 3)
i: 0
i: 0, j: 0, sum: 0
i: 0, j: 1, sum: 4
i: 0, j: 2, sum: 4
i: 0, j: 3, sum: 4
i: 1
i: 1, j: 1, sum: 0
i: 1, j: 2, sum: 4
i: 1, j: 3, sum: 4
i: 2
i: 2, j: 2, sum: 0
i: 2, j: 3, sum: 16
Solution: [1.5  3.   5.25 -inf]


/home/tone/www/ufsm/cadeiras/metodos-numericos/lib/sis_eq_lin/res_sistemas_triang.py:78: RuntimeWarning: divide by zero encountered in divide
  solution[-1] = self.vectorB[-1] / self.matrixA[-1][-1]
