In [1]:
import numpy as np
from lib.sis_eq_lin.res_sistemas_triang import ResSisLin


In [2]:
# Exemplo da aula
vec_solucao = np.array([-3, 5, 0])

matrizA = np.array([[3, 2, 4], [1, 1, 2], [4, 3, -2]])
vetorB = np.array([1, 2, 3])

triangularA = np.array([[3, 2, 4], [0, 1 / 3, 2 / 3], [0, 0, -8]])
vetorTriangularB = np.array([1, 5 / 3, 0])

In [3]:
ex1 = ResSisLin(triangularA, vetorTriangularB)

(3,) (3, 3)
Matriz é triangular superior
Received Matrix A:
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]]
Received Vector B:
[1.         1.66666667 0.        ]


In [4]:
ex1.findSolution()

Variation interval for I: range(1, -1, -1) with shape (0,2)
Initial Solution: [ 0.  0. -0.]
Array size 2
i: 1
i: 1, j: 2, sum: 0.0, solJ: -0.0
Solution of (1.6666666666666667 - 0.0 / 0.3333333333333333):
[ 0.  5. -0.]

i: 0
i: 0, j: 1, sum: 10.000000000000002, solJ: 5.000000000000001
i: 0, j: 2, sum: 10.000000000000002, solJ: -0.0
Solution of (1.0 - 10.000000000000002 / 3.0):
[-3.  5. -0.]

Solution: [-3.  5. -0.]


array([-3.,  5., -0.])

# Aula 22/05/2024

In [5]:
from lib.sis_eq_lin.met_eliminacao_gauss import MetodoEliminacaoGauss

In [6]:
# Exercício a)

a = np.array([[2,2,1,1],[1,-1,2,-1],[3,2,-3,-2],[4,3,2,1]])
b = np.array([7,1,4,12])

ex_a = MetodoEliminacaoGauss(a,b)

In [7]:
solutionMatrix, AUpper, BUpper = ex_a.findTriangular()


Solution matrix POS PIVOT CHANGES:
[[ 4.  3.  2.  1. 12.]
 [ 1. -1.  2. -1.  1.]
 [ 3.  2. -3. -2.  4.]
 [ 2.  2.  1.  1.  7.]]

Factor in [1,0]: 0.25
Linha i: [ 1. -1.  2. -1.  1.]
Linha j: [ 4.  3.  2.  1. 12.]
Final: [ 0.   -1.75  1.5  -1.25 -2.  ]
Solution matrix on [1,0]: 
 [[ 4.    3.    2.    1.   12.  ]
 [ 0.   -1.75  1.5  -1.25 -2.  ]
 [ 3.    2.   -3.   -2.    4.  ]
 [ 2.    2.    1.    1.    7.  ]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.    3.    2.    1.   12.  ]
 [ 0.   -1.75  1.5  -1.25 -2.  ]
 [ 3.    2.   -3.   -2.    4.  ]
 [ 2.    2.    1.    1.    7.  ]]

Factor in [2,0]: 0.75
Linha i: [ 3.  2. -3. -2.  4.]
Linha j: [ 4.  3.  2.  1. 12.]
Final: [ 0.   -0.25 -4.5  -2.75 -5.  ]
Solution matrix on [2,0]: 
 [[ 4.    3.    2.    1.   12.  ]
 [ 0.   -1.75  1.5  -1.25 -2.  ]
 [ 0.   -0.25 -4.5  -2.75 -5.  ]
 [ 2.    2.    1.    1.    7.  ]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.    3.    2.    1.   12.  ]
 [ 0.   -1.75  1.5  -1.25 -2.  ]
 [ 0.   -0.25 -4.5  -2.75 

In [8]:
ex_a_solution = ResSisLin(AUpper, BUpper)

(4, 1) (4, 4)
Matriz é triangular superior
Received Matrix A:
[[ 4.          3.          2.          1.        ]
 [ 0.         -1.75        1.5        -1.25      ]
 [ 0.          0.         -4.71428571 -2.57142857]
 [ 0.          0.          0.         -0.09090909]]
Received Vector B:
[[12.        ]
 [-2.        ]
 [-4.71428571]
 [ 0.        ]]


In [9]:
solution = ex_a_solution.findSolution()

Variation interval for I: range(2, -1, -1) with shape (0,3)
Initial Solution: [ 0.  0.  0. -0.]
Array size 3
i: 2
i: 2, j: 3, sum: 0.0, solJ: -0.0
Solution of ([-4.71428571] - 0.0 / -4.714285714285714):
[ 0.  0.  1. -0.]

i: 1
i: 1, j: 2, sum: 1.5, solJ: 1.0
i: 1, j: 3, sum: 1.5, solJ: -0.0
Solution of ([-2.] - 1.5 / -1.75):
[ 0.  2.  1. -0.]

i: 0
i: 0, j: 1, sum: 6.0, solJ: 2.0
i: 0, j: 2, sum: 8.0, solJ: 1.0
i: 0, j: 3, sum: 8.0, solJ: -0.0
Solution of ([12.] - 8.0 / 4.0):
[ 1.  2.  1. -0.]

Solution: [ 1.  2.  1. -0.]


In [10]:
# Ex livro

exlivro_a = np.array([[3, 2, 4], [1, 1, 2], [4, 3, -2]], dtype=float)
exlivro_b = np.array([1, 2, 3], dtype=float)

gauss_exlivro = MetodoEliminacaoGauss(exlivro_a, exlivro_b)


In [11]:
print(gauss_exlivro.augmentedMatrix)

[[ 3.  2.  4.  1.]
 [ 1.  1.  2.  2.]
 [ 4.  3. -2.  3.]]


In [12]:
solutionMatrix, AUpper, BUpper = gauss_exlivro.findTriangular()


Solution matrix POS PIVOT CHANGES:
[[ 4.  3. -2.  3.]
 [ 1.  1.  2.  2.]
 [ 3.  2.  4.  1.]]

Factor in [1,0]: 0.25
Linha i: [1. 1. 2. 2.]
Linha j: [ 4.  3. -2.  3.]
Final: [0.   0.25 2.5  1.25]
Solution matrix on [1,0]: 
 [[ 4.    3.   -2.    3.  ]
 [ 0.    0.25  2.5   1.25]
 [ 3.    2.    4.    1.  ]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.    3.   -2.    3.  ]
 [ 0.    0.25  2.5   1.25]
 [ 3.    2.    4.    1.  ]]

Factor in [2,0]: 0.75
Linha i: [3. 2. 4. 1.]
Linha j: [ 4.  3. -2.  3.]
Final: [ 0.   -0.25  5.5  -1.25]
Solution matrix on [2,0]: 
 [[ 4.    3.   -2.    3.  ]
 [ 0.    0.25  2.5   1.25]
 [ 0.   -0.25  5.5  -1.25]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.    3.   -2.    3.  ]
 [ 0.    0.25  2.5   1.25]
 [ 0.   -0.25  5.5  -1.25]]

Factor in [2,1]: -1.0
Linha i: [ 0.   -0.25  5.5  -1.25]
Linha j: [0.   0.25 2.5  1.25]
Final: [0. 0. 8. 0.]
Solution matrix on [2,1]: 
 [[ 4.    3.   -2.    3.  ]
 [ 0.    0.25  2.5   1.25]
 [ 0.    0.    8.    0.  ]] 

Solution Matrix:

In [13]:

print("A:\n", AUpper)
print("B:\n", BUpper)

A:
 [[ 4.    3.   -2.  ]
 [ 0.    0.25  2.5 ]
 [ 0.    0.    8.  ]]
B:
 [[3.  ]
 [1.25]
 [0.  ]]


In [14]:
solucao_exlivro = ResSisLin(AUpper, BUpper)

(3, 1) (3, 3)
Matriz é triangular superior
Received Matrix A:
[[ 4.    3.   -2.  ]
 [ 0.    0.25  2.5 ]
 [ 0.    0.    8.  ]]
Received Vector B:
[[3.  ]
 [1.25]
 [0.  ]]


In [15]:
solucao_exlivro.findSolution()

Variation interval for I: range(1, -1, -1) with shape (0,2)
Initial Solution: [0. 0. 0.]
Array size 2
i: 1
i: 1, j: 2, sum: 0.0, solJ: 0.0
Solution of ([1.25] - 0.0 / 0.25):
[0. 5. 0.]

i: 0
i: 0, j: 1, sum: 15.0, solJ: 5.0
i: 0, j: 2, sum: 15.0, solJ: 0.0
Solution of ([3.] - 15.0 / 4.0):
[-3.  5.  0.]

Solution: [-3.  5.  0.]


array([-3.,  5.,  0.])

In [16]:
# Ex 1 da aula 27/5
ex1_a = np.array([[2,2,1,1],[1,-1,2,-1],[3,2,-3,-2],[4,3,2,1]])
ex1_b = np.array([7,1,4,12])

print("--Método de eliminação de Gauss--")
gauss_ex1 = MetodoEliminacaoGauss(ex1_a, ex1_b)

print("Encontrando triangular:\n")
solutionMatrix, AUpper_ex1, BUpper_ex1 = gauss_ex1.findTriangular()

print("--Solucao do sistema--")
solucao_ex1 = ResSisLin(AUpper_ex1, BUpper_ex1)
solucao_ex1.findSolution()

--Método de eliminação de Gauss--
Encontrando triangular:


Solution matrix POS PIVOT CHANGES:
[[ 4.  3.  2.  1. 12.]
 [ 1. -1.  2. -1.  1.]
 [ 3.  2. -3. -2.  4.]
 [ 2.  2.  1.  1.  7.]]

Factor in [1,0]: 0.25
Linha i: [ 1. -1.  2. -1.  1.]
Linha j: [ 4.  3.  2.  1. 12.]
Final: [ 0.   -1.75  1.5  -1.25 -2.  ]
Solution matrix on [1,0]: 
 [[ 4.    3.    2.    1.   12.  ]
 [ 0.   -1.75  1.5  -1.25 -2.  ]
 [ 3.    2.   -3.   -2.    4.  ]
 [ 2.    2.    1.    1.    7.  ]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.    3.    2.    1.   12.  ]
 [ 0.   -1.75  1.5  -1.25 -2.  ]
 [ 3.    2.   -3.   -2.    4.  ]
 [ 2.    2.    1.    1.    7.  ]]

Factor in [2,0]: 0.75
Linha i: [ 3.  2. -3. -2.  4.]
Linha j: [ 4.  3.  2.  1. 12.]
Final: [ 0.   -0.25 -4.5  -2.75 -5.  ]
Solution matrix on [2,0]: 
 [[ 4.    3.    2.    1.   12.  ]
 [ 0.   -1.75  1.5  -1.25 -2.  ]
 [ 0.   -0.25 -4.5  -2.75 -5.  ]
 [ 2.    2.    1.    1.    7.  ]] 


Solution matrix POS PIVOT CHANGES:
[[ 4.    3.    2.    1.   12.  ]


array([ 1.,  2.,  1., -0.])

In [17]:
# Ex 2 da aula 27/5 - depende de pivotamento

pivo_a = np.array([[0, -2, 5, 1], [-6, 4, -8, 1], [9, -6, 19, 1], [6, -4, -6, 15]])

pivo_b = np.array([7, -9, 23, 11])
print("--Método de eliminação de Gauss--")
gauss_pivo = MetodoEliminacaoGauss(pivo_a, pivo_b)

print("Encontrando triangular:\n")
solutionMatrix, AUpperPivo, BUpperPivo = gauss_pivo.findTriangular()

--Método de eliminação de Gauss--
Encontrando triangular:


Solution matrix POS PIVOT CHANGES:
[[ 9. -6. 19.  1. 23.]
 [-6.  4. -8.  1. -9.]
 [ 0. -2.  5.  1.  7.]
 [ 6. -4. -6. 15. 11.]]

Factor in [1,0]: -0.6666666666666666
Linha i: [-6.  4. -8.  1. -9.]
Linha j: [ 9. -6. 19.  1. 23.]
Final: [0.         0.         4.66666667 1.66666667 6.33333333]
Solution matrix on [1,0]: 
 [[ 9.         -6.         19.          1.         23.        ]
 [ 0.          0.          4.66666667  1.66666667  6.33333333]
 [ 0.         -2.          5.          1.          7.        ]
 [ 6.         -4.         -6.         15.         11.        ]] 


Solution matrix POS PIVOT CHANGES:
[[ 9.         -6.         19.          1.         23.        ]
 [ 0.          0.          4.66666667  1.66666667  6.33333333]
 [ 0.         -2.          5.          1.          7.        ]
 [ 6.         -4.         -6.         15.         11.        ]]

Factor in [2,0]: 0.0
Linha i: [ 0. -2.  5.  1.  7.]
Linha j: [ 9. -6. 19.  

In [18]:
print("--Solucao do sistema--")
solucao_pivo = ResSisLin(AUpperPivo, BUpperPivo)
solucao_final_pivo = solucao_pivo.findSolution()

--Solucao do sistema--
(4, 1) (4, 4)
Matriz é triangular superior
Received Matrix A:
[[  9.          -6.          19.           1.        ]
 [  0.          -2.           5.           1.        ]
 [  0.           0.         -18.66666667  14.33333333]
 [  0.           0.           0.           5.25      ]]
Received Vector B:
[[23.        ]
 [ 7.        ]
 [-4.33333333]
 [ 5.25      ]]
Variation interval for I: range(2, -1, -1) with shape (0,3)
Initial Solution: [0. 0. 0. 1.]
Array size 3
i: 2
i: 2, j: 3, sum: 14.33333333333333, solJ: 0.9999999999999998
Solution of ([-4.33333333] - 14.33333333333333 / -18.666666666666664):
[0. 0. 1. 1.]

i: 1
i: 1, j: 2, sum: 5.0, solJ: 1.0
i: 1, j: 3, sum: 6.0, solJ: 0.9999999999999998
Solution of ([7.] - 6.0 / -2.0):
[ 0.  -0.5  1.   1. ]

i: 0
i: 0, j: 1, sum: 3.0, solJ: -0.5
i: 0, j: 2, sum: 22.0, solJ: 1.0
i: 0, j: 3, sum: 23.0, solJ: 0.9999999999999998
Solution of ([23.] - 23.0 / 9.0):
[ 0.  -0.5  1.   1. ]

Solution: [ 0.  -0.5  1.   1. ]
